set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKe2wqhnxpkjp87b3eyfq6gl39a;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKes16tfhb67qqf7lqx6t6uk7cv;
alter table if exists Customer_CreditCard drop constraint if exists FKlsjp44vhufgo7x9ua27827f39;
alter table if exists Customer_CreditCard drop constraint if exists FKe68ll9m52hsej9o3f2p6vb6ft;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists Customer_CreditCard cascade;
drop table if exists Pincode cascade;
set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKe2wqhnxpkjp87b3eyfq6gl39a;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKes16tfhb67qqf7lqx6t6uk7cv;
alter table if exists Customer_CreditCard drop constraint if exists FKlsjp44vhufgo7x9ua27827f39;
alter table if exists Customer_CreditCard drop constraint if exists FKe68ll9m52hsej9o3f2p6vb6ft;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists Customer_CreditCard cascade;
drop table if exists Pincode cascade;
set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKe2wqhnxpkjp87b3eyfq6gl39a;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKes16tfhb67qqf7lqx6t6uk7cv;
alter table if exists Customer_CreditCard drop constraint if exists FKlsjp44vhufgo7x9ua27827f39;
alter table if exists Customer_CreditCard drop constraint if exists FKe68ll9m52hsej9o3f2p6vb6ft;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists Customer_CreditCard cascade;
drop table if exists Pincode cascade;
set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKe2wqhnxpkjp87b3eyfq6gl39a;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKes16tfhb67qqf7lqx6t6uk7cv;
alter table if exists Customer_CreditCard drop constraint if exists FKlsjp44vhufgo7x9ua27827f39;
alter table if exists Customer_CreditCard drop constraint if exists FKe68ll9m52hsej9o3f2p6vb6ft;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists Customer_CreditCard cascade;
drop table if exists Pincode cascade;
set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKe2wqhnxpkjp87b3eyfq6gl39a;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKes16tfhb67qqf7lqx6t6uk7cv;
alter table if exists Customer_CreditCard drop constraint if exists FKlsjp44vhufgo7x9ua27827f39;
alter table if exists Customer_CreditCard drop constraint if exists FKe68ll9m52hsej9o3f2p6vb6ft;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists Customer_CreditCard cascade;
drop table if exists Pincode cascade;
set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKe2wqhnxpkjp87b3eyfq6gl39a;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKes16tfhb67qqf7lqx6t6uk7cv;
alter table if exists Customer_CreditCard drop constraint if exists FKlsjp44vhufgo7x9ua27827f39;
alter table if exists Customer_CreditCard drop constraint if exists FKe68ll9m52hsej9o3f2p6vb6ft;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists Customer_CreditCard cascade;
drop table if exists Pincode cascade;
set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKe2wqhnxpkjp87b3eyfq6gl39a;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKes16tfhb67qqf7lqx6t6uk7cv;
alter table if exists Customer_CreditCard drop constraint if exists FKlsjp44vhufgo7x9ua27827f39;
alter table if exists Customer_CreditCard drop constraint if exists FKe68ll9m52hsej9o3f2p6vb6ft;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists Customer_CreditCard cascade;
drop table if exists Pincode cascade;
set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKe2wqhnxpkjp87b3eyfq6gl39a;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKes16tfhb67qqf7lqx6t6uk7cv;
alter table if exists Customer_CreditCard drop constraint if exists FKlsjp44vhufgo7x9ua27827f39;
alter table if exists Customer_CreditCard drop constraint if exists FKe68ll9m52hsej9o3f2p6vb6ft;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists Customer_CreditCard cascade;
drop table if exists Pincode cascade;
set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKe2wqhnxpkjp87b3eyfq6gl39a;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKes16tfhb67qqf7lqx6t6uk7cv;
alter table if exists Customer_CreditCard drop constraint if exists FKlsjp44vhufgo7x9ua27827f39;
alter table if exists Customer_CreditCard drop constraint if exists FKe68ll9m52hsej9o3f2p6vb6ft;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists Customer_CreditCard cascade;
drop table if exists Pincode cascade;
